version: 2
updates:
  - package-ecosystem: "pnpm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    package-manager: "pnpm"
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"
    open-pull-requests-limit: 10
    versioning-strategy: auto
    rebase-strategy: auto

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "automated"
      - "github-actions"
    open-pull-requests-limit: 10
    rebase-strategy: auto 