packages:
  - docs

overrides:
  diff@<4.0.4: '>=4.0.4'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  mdast-util-to-hast@>=13.0.0 <13.2.1: '>=13.2.1'
  node-forge@<1.3.2: '>=1.3.2'
  qs@<6.14.1: '>=6.14.1'
  undici@>=7.0.0 <7.18.2: '>=7.18.2'
