export const CarrotVesting = <const>[
  {
    type: 'function',
    name: 'owner',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', simpleType: 'address' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'calculateClaimableAmount',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'user', simpleType: 'address' }],
    outputs: [{ type: 'uint128', name: '', simpleType: 'uint' }],
  },
  {
    type: 'function',
    name: 'EXCHANGE_RATE',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'claim',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint128', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'CARROT',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', simpleType: 'address' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'PUFFER',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', simpleType: 'address' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'TOTAL_PUFFER_REWARDS',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'steps',
    stateMutability: 'view',
    outputs: [{ type: 'uint32', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'MAX_CARROT_AMOUNT',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'vestings',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'user', simpleType: 'address' }],
    outputs: [
      { type: 'uint128', name: 'depositedAmount', simpleType: 'uint' },
      { type: 'uint128', name: 'claimedAmount', simpleType: 'uint' },
      { type: 'uint48', name: 'lastClaimedTimestamp', simpleType: 'uint' },
      { type: 'uint48', name: 'depositedTimestamp', simpleType: 'uint' },
    ],
  },
  {
    type: 'function',
    name: 'startTimestamp',
    stateMutability: 'view',
    outputs: [{ type: 'uint48', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'startVesting',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'uint256', name: 'amount', simpleType: 'uint' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'totalDepositedAmount',
    stateMutability: 'view',
    outputs: [{ type: 'uint128', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'duration',
    stateMutability: 'view',
    outputs: [{ type: 'uint32', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'startVestingWithPermit',
    stateMutability: 'nonpayable',
    inputs: [
      {
        type: 'tuple',
        name: 'permitData',
        simpleType: 'tuple',
        components: [
          { type: 'uint256', name: 'deadline', simpleType: 'uint' },
          { type: 'uint256', name: 'amount', simpleType: 'uint' },
          { type: 'uint8', name: 'v', simpleType: 'uint' },
          { type: 'bytes32', name: 'r', simpleType: 'bytes' },
          { type: 'bytes32', name: 's', simpleType: 'bytes' },
        ],
      },
    ],
    outputs: [],
  },
];
