export const CarrotVesting = <const>[
  {
    type: 'function',
    name: 'calculateClaimableAmount',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'user', simpleType: 'address' }],
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
  },
  {
    type: 'function',
    name: 'PUFFER',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', simpleType: 'address' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'claim',
    stateMutability: 'nonpayable',
    outputs: [{ type: 'uint128', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'owner',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', simpleType: 'address' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'getTotalDepositedAmount',
    stateMutability: 'view',
    outputs: [{ type: 'uint128', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'getVestings',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'user', simpleType: 'address' }],
    outputs: [
      {
        type: 'tuple[]',
        name: '',
        simpleType: 'slice',
        nestedType: { type: 'tuple' },
        components: [
          { type: 'uint128', name: 'depositedAmount', simpleType: 'uint' },
          { type: 'uint128', name: 'claimedAmount', simpleType: 'uint' },
          { type: 'uint48', name: 'lastClaimedTimestamp', simpleType: 'uint' },
          { type: 'uint48', name: 'depositedTimestamp', simpleType: 'uint' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'TOTAL_PUFFER_REWARDS',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'getDuration',
    stateMutability: 'view',
    outputs: [{ type: 'uint32', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'getNewDuration',
    stateMutability: 'view',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'startVesting',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'uint256', name: 'amount', simpleType: 'uint' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getSteps',
    stateMutability: 'view',
    outputs: [{ type: 'uint32', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    inputs: [],
    name: 'getNewSteps',
    outputs: [{ internalType: 'uint32', name: '', type: 'uint32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getUpgradeTimestamp',
    outputs: [{ internalType: 'uint48', name: '', type: 'uint48' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    type: 'function',
    name: 'EXCHANGE_RATE',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'startVestingWithPermit',
    stateMutability: 'nonpayable',
    inputs: [
      {
        type: 'tuple',
        name: 'permitData',
        simpleType: 'tuple',
        components: [
          { type: 'uint256', name: 'deadline', simpleType: 'uint' },
          { type: 'uint256', name: 'amount', simpleType: 'uint' },
          { type: 'uint8', name: 'v', simpleType: 'uint' },
          { type: 'bytes32', name: 'r', simpleType: 'bytes' },
          { type: 'bytes32', name: 's', simpleType: 'bytes' },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'CARROT',
    stateMutability: 'view',
    outputs: [{ type: 'address', name: '', simpleType: 'address' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'getStartTimestamp',
    stateMutability: 'view',
    outputs: [{ type: 'uint48', name: '', simpleType: 'uint' }],
    inputs: [],
  },
  {
    type: 'function',
    name: 'MAX_CARROT_AMOUNT',
    stateMutability: 'view',
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
    inputs: [],
  },
];
