export const GuardianModule = <const>[
  {
    inputs: [],
    name: 'getEjectionThreshold',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getGuardians',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'guardian', type: 'address' }],
    name: 'getGuardiansEnclaveAddress',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getGuardiansEnclaveAddresses',
    outputs: [{ internalType: 'address[]', name: '', type: 'address[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getGuardiansEnclavePubkeys',
    outputs: [{ internalType: 'bytes[]', name: '', type: 'bytes[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getMrenclave',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getMrsigner',
    outputs: [{ internalType: 'bytes32', name: '', type: 'bytes32' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getThreshold',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'isConsumingScheduledOp',
    outputs: [{ internalType: 'bytes4', name: '', type: 'bytes4' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'account', type: 'address' }],
    name: 'isGuardian',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'guardian', type: 'address' }],
    name: 'removeGuardian',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'blockNumber', type: 'uint256' },
      { internalType: 'bytes', name: 'pubKey', type: 'bytes' },
      {
        components: [
          { internalType: 'bytes', name: 'report', type: 'bytes' },
          { internalType: 'bytes', name: 'signature', type: 'bytes' },
          {
            internalType: 'bytes32',
            name: 'leafX509CertDigest',
            type: 'bytes32',
          },
        ],
        internalType: 'struct RaveEvidence',
        name: 'evidence',
        type: 'tuple',
      },
    ],
    name: 'rotateGuardianKey',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'splitGuardianFunds',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      {
        components: [
          { internalType: 'address', name: 'module', type: 'address' },
          { internalType: 'uint256', name: 'startEpoch', type: 'uint256' },
          { internalType: 'uint256', name: 'endEpoch', type: 'uint256' },
          { internalType: 'bool', name: 'wasSlashed', type: 'bool' },
          { internalType: 'bytes32', name: 'moduleName', type: 'bytes32' },
          {
            internalType: 'uint256',
            name: 'pufferModuleIndex',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'withdrawalAmount',
            type: 'uint256',
          },
        ],
        internalType: 'struct StoppedValidatorInfo[]',
        name: 'validatorInfos',
        type: 'tuple[]',
      },
      { internalType: 'bytes[]', name: 'eoaSignatures', type: 'bytes[]' },
    ],
    name: 'validateBatchWithdrawals',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes[]', name: 'eoaSignatures', type: 'bytes[]' },
      { internalType: 'bytes32', name: 'signedMessageHash', type: 'bytes32' },
    ],
    name: 'validateGuardiansEOASignatures',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes[]', name: 'enclaveSignatures', type: 'bytes[]' },
      { internalType: 'bytes32', name: 'signedMessageHash', type: 'bytes32' },
    ],
    name: 'validateGuardiansEnclaveSignatures',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'pufferModuleIndex', type: 'uint256' },
      { internalType: 'bytes', name: 'pubKey', type: 'bytes' },
      { internalType: 'bytes', name: 'signature', type: 'bytes' },
      { internalType: 'bytes', name: 'withdrawalCredentials', type: 'bytes' },
      { internalType: 'bytes32', name: 'depositDataRoot', type: 'bytes32' },
      { internalType: 'bytes[]', name: 'enclaveSignatures', type: 'bytes[]' },
    ],
    name: 'validateProvisionNode',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'bytes32', name: 'moduleName', type: 'bytes32' },
      { internalType: 'uint256', name: 'skippedIndex', type: 'uint256' },
      { internalType: 'bytes[]', name: 'eoaSignatures', type: 'bytes[]' },
    ],
    name: 'validateSkipProvisioning',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      {
        internalType: 'uint256',
        name: 'newNumberOfValidators',
        type: 'uint256',
      },
      { internalType: 'uint256', name: 'epochNumber', type: 'uint256' },
      { internalType: 'bytes[]', name: 'eoaSignatures', type: 'bytes[]' },
    ],
    name: 'validateTotalNumberOfValidators',
    outputs: [],
    stateMutability: 'view',
    type: 'function',
  },
];
