export const vlPUFFER = <const>[
  {
    type: 'function',
    name: 'PUFFER',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address', name: '', simpleType: 'address' }],
  },
  {
    type: 'function',
    name: 'decimals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8', name: '', simpleType: 'uint' }],
  },
  {
    type: 'function',
    name: 'delegates',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'account', simpleType: 'address' }],
    outputs: [{ type: 'address', name: '', simpleType: 'address' }],
  },
  {
    type: 'function',
    name: 'owner',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address', name: '', simpleType: 'address' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { type: 'address', name: 'owner', simpleType: 'address' },
      { type: 'address', name: 'spender', simpleType: 'address' },
    ],
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
  },
  {
    type: 'function',
    name: 'transferFrom',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'from', simpleType: 'address' },
      { type: 'address', name: 'to', simpleType: 'address' },
      { type: 'uint256', name: 'value', simpleType: 'uint' },
    ],
    outputs: [{ type: 'bool', name: '', simpleType: 'bool' }],
  },
  {
    type: 'function',
    name: 'totalSupply',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
  },
  {
    type: 'function',
    name: 'createLock',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'uint256', name: 'amount', simpleType: 'uint' },
      { type: 'uint256', name: 'multiplier', simpleType: 'uint' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'symbol',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'string', name: '', simpleType: 'string' }],
  },
  {
    type: 'function',
    name: 'paused',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'bool', name: '', simpleType: 'bool' }],
  },
  {
    type: 'function',
    name: 'lockInfos',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'user', simpleType: 'address' }],
    outputs: [
      { type: 'uint256', name: 'pufferAmount', simpleType: 'uint' },
      { type: 'uint256', name: 'unlockTime', simpleType: 'uint' },
    ],
  },
  {
    type: 'function',
    name: 'getPastTotalSupply',
    stateMutability: 'view',
    inputs: [{ type: 'uint256', name: 'timepoint', simpleType: 'uint' }],
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
  },
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'account', simpleType: 'address' }],
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
  },
  {
    type: 'function',
    name: 'nonces',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'owner', simpleType: 'address' }],
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
  },
  {
    type: 'function',
    name: 'getVotes',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'account', simpleType: 'address' }],
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
  },
  {
    type: 'function',
    name: 'delegateBySig',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'delegatee', simpleType: 'address' },
      { type: 'uint256', name: 'nonce', simpleType: 'uint' },
      { type: 'uint256', name: 'expiry', simpleType: 'uint' },
      { type: 'uint8', name: 'v', simpleType: 'uint' },
      { type: 'bytes32', name: 'r', simpleType: 'bytes' },
      { type: 'bytes32', name: 's', simpleType: 'bytes' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'pause',
    stateMutability: 'nonpayable',
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'transfer',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'to', simpleType: 'address' },
      { type: 'uint256', name: 'value', simpleType: 'uint' },
    ],
    outputs: [{ type: 'bool', name: '', simpleType: 'bool' }],
  },
  {
    type: 'function',
    name: 'CLOCK_MODE',
    stateMutability: 'pure',
    inputs: [],
    outputs: [{ type: 'string', name: '', simpleType: 'string' }],
  },
  {
    type: 'function',
    name: 'numCheckpoints',
    stateMutability: 'view',
    inputs: [{ type: 'address', name: 'account', simpleType: 'address' }],
    outputs: [{ type: 'uint32', name: '', simpleType: 'uint' }],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'address', name: 'spender', simpleType: 'address' },
      { type: 'uint256', name: 'value', simpleType: 'uint' },
    ],
    outputs: [{ type: 'bool', name: '', simpleType: 'bool' }],
  },
  {
    type: 'function',
    name: 'reLock',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'uint256', name: 'amount', simpleType: 'uint' },
      { type: 'uint256', name: 'multiplier', simpleType: 'uint' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getPastVotes',
    stateMutability: 'view',
    inputs: [
      { type: 'address', name: 'account', simpleType: 'address' },
      { type: 'uint256', name: 'timepoint', simpleType: 'uint' },
    ],
    outputs: [{ type: 'uint256', name: '', simpleType: 'uint' }],
  },
  {
    type: 'function',
    name: 'checkpoints',
    stateMutability: 'view',
    inputs: [
      { type: 'address', name: 'account', simpleType: 'address' },
      { type: 'uint32', name: 'pos', simpleType: 'uint' },
    ],
    outputs: [
      {
        type: 'tuple',
        name: '',
        simpleType: 'tuple',
        components: [
          { type: 'uint48', name: '_key', simpleType: 'uint' },
          { type: 'uint208', name: '_value', simpleType: 'uint' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'name',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'string', name: '', simpleType: 'string' }],
  },
  {
    type: 'function',
    name: 'createLockWithPermit',
    stateMutability: 'nonpayable',
    inputs: [
      { type: 'uint256', name: 'value', simpleType: 'uint' },
      { type: 'uint256', name: 'multiplier', simpleType: 'uint' },
      {
        type: 'tuple',
        name: 'permitData',
        simpleType: 'tuple',
        components: [
          { type: 'uint256', name: 'deadline', simpleType: 'uint' },
          { type: 'uint256', name: 'amount', simpleType: 'uint' },
          { type: 'uint8', name: 'v', simpleType: 'uint' },
          { type: 'bytes32', name: 'r', simpleType: 'bytes' },
          { type: 'bytes32', name: 's', simpleType: 'bytes' },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'clock',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint48', name: '', simpleType: 'uint' }],
  },
  {
    type: 'function',
    name: 'withdraw',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'address', name: 'recipient', simpleType: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'delegate',
    stateMutability: 'nonpayable',
    inputs: [{ type: 'address', name: 'delegatee', simpleType: 'address' }],
    outputs: [],
  },
];
